"""empty message

Revision ID: 95c7163e6f8b
Revises: c727601f2513
Create Date: 2018-10-29 21:26:23.546584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c7163e6f8b'
down_revision = 'c727601f2513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brewery_venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brewery_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brewery_id'], ['brewery.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('venue', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'longitude')
    op.drop_column('venue', 'latitude')
    op.drop_table('brewery_venue')
    # ### end Alembic commands ###
