import enum

class BeerType(enum.Enum):
    BELGIAN_STRONG_GOLDEN_ALE = 'Belgian Strong Golden Ale'
    CALIFORNIA_COMMON = 'California Common'
    ENGLISH_BITTER = 'English Bitter'
    HEFEWEIZEN = 'Hefeweizen'
    IPA_ENGLISH = 'IPA - English'
    IPA_AMERICAN = 'IPA - American'
    IPA_IMPERIAL_DOUBLE = 'IPA - Imperial / Double'
    IPA_SESSION = 'IPA - Session / India Session Ale'
    LAGER_AMERICAN_LIGHT = 'Lager - American Light'
    LAGER_EURO = 'Lager - Euro'
    LAGER_NA_ADJUNCT = 'Lager - North American Adjunct'
    LAGER_PALE = 'Lager - Pale'
    LAGER_VIENNA = 'Lager - Vienna'
    LAGER_WINTER = 'Lager - Winter'
    MARZEN = 'Märzen'
    PALE_ALE_AMERICAN = 'Pale Ale - American'
    PALE_WHEAT_ALE_AMERICAN = 'Pale Wheat Ale - American'
    PILSNER_GERMAN = 'Pilsner - German'
    PORTER_AMERICAN = 'Porter - American'
    PUMPKIN_YAM = 'Pumpkin / Yam Beer'
    RED_ALE_AMERICAN_AMBER_RED = 'Red Ale - American Amber / Red'
    ROOT_BEER = 'Root Beer'
    SHANDY_RADLER = 'Shandy / Radler'
    STOUT_AMERICAN_IMPERIAL_DOUBLE = 'Stout - American Imperial / Double'
    STOUT_IMPERIAL_MILK_SWEET = 'Stout - Imperial Milk / Sweet'
    WITBIER = 'Witbier'   

class SocialMediaType(enum.Enum):
    FACEBOOK = 'Facebook'
    TWITTER = 'Twitter'
    INSTAGRAM = 'Instagram'
    GOOGLE = 'Google'

class VenueType(enum.Enum):
    AMERICAN_RESTAURANT = 'American Restaurant'
    ARCARDE = 'Arcade'
    BAR = 'Bar'
    BEER_GARDEN = 'Beer Garden'
    BOAT_OR_FERRY = 'Boat or Ferry'
    BOTANICAL_GARDEN = 'Botanical Garden'
    BOWLING_ALLEY = 'Bowling Alley'
    BREAKFAST_SPOT = 'Breakfast Spot'
    BREWERY = 'Brewery'
    CAFE = 'Café'
    FISH_AND_CHIPS_SHOP = 'Fish & Chips Shop'
    GASTROPUB = 'Gastropub'
    GENERAL_ENTERTAINMENT = 'General Entertainment'
    HOTEL = 'Hotel'
    IRISH_PUB = 'Irish Pub'
    ITALIAN_RESTAURANT = 'Italian Restaurant'
    LOUNGE = 'Lounge'
    MUSEUM = 'Museum'
    PUB = 'Pub'
    SEAFOOD_RESTAURANT = 'Seafood Restaurant'
    SHOPPING_MALL = 'Shopping Mall'
    SPORTS_BAR = 'Sports Bar'
    TEX_MEX_RESTAURANT = 'Tex-Mex Restaurant'
    
class BreweryType(enum.Enum):
    BREW_PUB = 'Brew Pub'
    HOME = 'Home Brewery'
    MACRO = 'Macro Brewery'
    MICRO = 'Micro Brewery'
    REGIONAL = 'Regional Brewery'

class ServingType(enum.Enum):
    BOTTLE = 'Bottle'
    DRAFT = 'Draft'
    TASTER = 'Taster'
    CAN = 'Can'